url: http://aprodeweb.github.io/laconferenciarails.es
exclude: ["Gemfile","Gemfile.lock",".ruby-version",".ruby-gemset"]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
