url: http://conferenciaror.es
gems: [bourbon, neat]
exclude: ["Gemfile","Gemfile.lock",".ruby-version",".ruby-gemset"]
style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
sass:
  style: compressed
  # sass_dir: _sass # default _sass
