url: http://conferenciaror.es
exclude: ["Gemfile","Gemfile.lock",".ruby-version",".ruby-gemset"]
style: compressed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      values:
      layout: "default"
sass:
  sass_dir: _sass
  style: compressed
